import test from "node:test";
import assert from "node:assert/strict";
import { readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));

// Everything in data/ is generated by scripts/fetch-*.mjs, never hand-edited.
// Indentation there is bytes on the cold-load path that nothing reads, so all
// three writers emit a single line.
test("every snapshot ships as one line with a trailing newline", () => {
  const files = readdirSync(join(ROOT, "data")).filter((name) => name.endsWith(".json"));
  assert.ok(files.length > 0, "no snapshots found");

  for (const name of files) {
    const text = readFileSync(join(ROOT, "data", name), "utf8");
    assert.match(text, /\n$/, `${name} has no trailing newline`);
    // A checkout on Windows carries CRLF.
    assert.equal(text.split(/\r?\n/).length, 2, `${name} is not on one line`);
  }
});

// The check above only goes red the morning after a nightly run has already
// committed the bloated file, so pin the writers themselves too.
test("every snapshot writer serializes at indent 0", () => {
  for (const name of ["fetch-courses.mjs", "fetch-ratings.mjs", "fetch-seats.mjs"]) {
    const source = readFileSync(join(ROOT, "scripts", name), "utf8");
    const calls = [...source.matchAll(/JSON\.stringify\([^)]+,\s*null,\s*(\d+)\)/g)];
    assert.ok(calls.length > 0, `${name} has no snapshot serialization`);

    for (const [call, indent] of calls) assert.equal(indent, "0", `${name}: ${call}`);
  }
});
